version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Install prototool
          command: |
            curl -sSL https://github.com/uber/prototool/releases/download/v1.0.0/prototool-$(uname -s)-$(uname -m) -o ./prototool
            chmod +x ./prototool
      - run:
          name: Format a proto file and compile with protoc to check for failure
          command: ./prototool format -d
